name: Build and test

on: [push, pull_request, workflow_dispatch]

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  standard-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - "--enable-debug --enable-cuckoo --enable-magic --enable-pb-tests --enable-address-sanitizer --enable-undefined-behaviour-sanitizer"
        - "--enable-debug --enable-profiling --enable-cuckoo --enable-magic --enable-pb-tests --enable-address-sanitizer --enable-undefined-behaviour-sanitizer"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            gcc-multilib \
            libtool \
            libjansson-dev \
            libmagic-dev \
            libssl-dev  \
            protobuf-compiler \
            protobuf-c-compiler \
            libprotobuf-c-dev
      - name: Print versions
        run: |
          bison --version
          gcc --version
      - name: Prepare for building
        run: |
          ./bootstrap.sh
          ./configure ${{ matrix.config }}
      - name: Build
        run: make clean && make

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: standard-build-${{ matrix.config }}
          path: ${{ github.workspace }}

      - name: Run tests
        run: make check
      - name: Print tests errors
        if: ${{ failure() }}
        run: cat test-suite.log

  mingw-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - "--host=x86_64-w64-mingw32"
        - "--host=i686-w64-mingw32"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            libssl-dev  \
            gcc-mingw-w64
      - name: Prepare for building
        run: |
          ./bootstrap.sh
          ./configure ${{ matrix.config }}
      - name: Build
        run: make clean && make

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mingw-build-${{ matrix.config }}
          path: ${{ github.workspace }}
