name: Build and test

on: [push, pull_request, workflow_dispatch]

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  mingw-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - "--host=x86_64-w64-mingw32"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            libssl-dev  \
            gcc-mingw-w64
      - name: Prepare for building
        run: |
          ./bootstrap.sh
          ./configure ${{ matrix.config }}
      - name: Build
        run: make clean && make

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mingw-build-${{ matrix.config }}
          path: ${{ github.workspace }}/.libs
